export default `
DROP TABLE IF EXISTS __SCHEMA__.audio CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.changesets CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.choice_lists CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.classification_sets CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.forms CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.memberships CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.photos CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.projects CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.roles CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.signatures CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.videos CASCADE;
DROP TABLE IF EXISTS __SCHEMA__.records CASCADE;
`;
